/**
 * Code templates for the typed client generator.
 */

export const FILE_HEADER = `// Auto-generated by horizon-drupal-client codegen.
// Run \`npx horizon-schema sync\` to regenerate.
// DO NOT EDIT — changes will be overwritten.

import type { HorizonClient } from 'horizon-drupal-client'
import type { DrupalNode, DrupalParagraph, DrupalTerm } from 'horizon-drupal-client'
import type { Text, TextSummary, Image, Link, DateTime, Address, Geofield, DateRange, MediaImage, MediaVideo } from 'horizon-drupal-client'
import type { QueryOptions } from 'horizon-drupal-client'
`

export const TYPED_CLIENT_INTERFACE = `
// ─── Typed Client ──────────────────────────────────────────────────

export interface TypedClient {
  /** List content entries of a given type */
  getEntries<K extends ContentTypeName>(
    type: K,
    options?: QueryOptions,
  ): Promise<ContentTypeMap[K][]>

  /** Get a single content entry by UUID */
  getEntry<K extends ContentTypeName>(
    type: K,
    id: string,
  ): Promise<ContentTypeMap[K] | null>

  /** Resolve a Drupal path to a typed content node */
  getByPath(path: string): Promise<ContentNode | null>

  /** Get a landing/article page by path (includes paragraph content) */
  getPage(path: string): Promise<ContentNode | null>

  /** Escape hatch: run a raw GraphQL query */
  raw<T = any>(query: string, variables?: Record<string, any>): Promise<T>
}
`

export const CREATE_TYPED_CLIENT = `
// ─── Dealias helper ────────────────────────────────────────────────

/**
 * Recursively strip alias prefixes from response keys.
 * Converts "card_title" → "title", "card_displayType" → "displayType", etc.
 * Aliases follow the pattern: {typeName}_{fieldName} where typeName comes
 * from the __typename (e.g. ParagraphCard → "card").
 */
function dealiasResponse(obj: any): any {
  if (obj === null || obj === undefined) return obj
  if (Array.isArray(obj)) return obj.map(dealiasResponse)
  if (typeof obj !== 'object') return obj

  const result: any = {}
  // Determine prefix from __typename if present
  const typeName = obj.__typename as string | undefined
  let prefix = ''
  if (typeName?.startsWith('Paragraph')) {
    const base = typeName.replace('Paragraph', '')
    prefix = base.charAt(0).toLowerCase() + base.slice(1) + '_'
  }

  for (const [key, value] of Object.entries(obj)) {
    // Strip alias prefix if it matches this type's prefix
    let cleanKey = key
    if (prefix && key.startsWith(prefix)) {
      cleanKey = key.slice(prefix.length)
    }
    // Also strip any other common alias patterns (prefix_field format)
    if (cleanKey === key && key.includes('_') && !key.startsWith('__')) {
      const underscoreIdx = key.indexOf('_')
      const possibleField = key.slice(underscoreIdx + 1)
      // Only strip if the part before _ looks like a type prefix (lowercase start)
      if (key.charAt(0) === key.charAt(0).toLowerCase() && possibleField.length > 0) {
        cleanKey = possibleField
      }
    }
    result[cleanKey] = dealiasResponse(value)
  }
  return result
}

// ─── Factory ───────────────────────────────────────────────────────

export function createTypedClient(client: HorizonClient): TypedClient {
  return {
    async getEntries(type, options) {
      const config = QUERIES[type]
      if (!config) throw new Error(\`No query defined for type: \${type}\`)
      const data = await client.query(config.list, options)
      const key = Object.keys(data)[0]
      return data[key]?.nodes ?? []
    },
    async getEntry(type, id) {
      const config = QUERIES[type]
      if (!config) throw new Error(\`No query defined for type: \${type}\`)
      const data = await client.query(config.single, { id })
      const key = Object.keys(data)[0]
      return data[key] ?? null
    },
    async getByPath(path) {
      return client.queryByPath(path, ROUTE_QUERY)
    },
    async getPage(path) {
      const entity = await client.queryByPath(path, PAGE_QUERY)
      return entity ? dealiasResponse(entity) : null
    },
    async raw(query, variables) {
      return client.query(query, variables)
    },
  }
}
`
