/**
 * Code templates for the typed client generator.
 */

export const FILE_HEADER = `// Auto-generated by horizon-drupal-client codegen.
// Run \`npx horizon-schema sync\` to regenerate.
// DO NOT EDIT — changes will be overwritten.

import type { HorizonClient } from 'horizon-drupal-client'
import type { DrupalNode, DrupalParagraph, DrupalTerm } from 'horizon-drupal-client'
import type { Text, TextSummary, Image, Link, DateTime, Address, Geofield, DateRange } from 'horizon-drupal-client'
import type { QueryOptions } from 'horizon-drupal-client'
`

export const TYPED_CLIENT_INTERFACE = `
// ─── Typed Client ──────────────────────────────────────────────────

export interface TypedClient {
  /** List content entries of a given type */
  getEntries<K extends ContentTypeName>(
    type: K,
    options?: QueryOptions,
  ): Promise<ContentTypeMap[K][]>

  /** Get a single content entry by UUID */
  getEntry<K extends ContentTypeName>(
    type: K,
    id: string,
  ): Promise<ContentTypeMap[K] | null>

  /** Resolve a Drupal path to a typed content node */
  getByPath(path: string): Promise<ContentNode | null>

  /** Get a landing/article page by path (includes paragraph content) */
  getPage(path: string): Promise<ContentNode | null>

  /** Escape hatch: run a raw GraphQL query */
  raw<T = any>(query: string, variables?: Record<string, any>): Promise<T>
}
`

export const CREATE_TYPED_CLIENT = `
// ─── Factory ───────────────────────────────────────────────────────

export function createTypedClient(client: HorizonClient): TypedClient {
  return {
    async getEntries(type, options) {
      const config = QUERIES[type]
      if (!config) throw new Error(\`No query defined for type: \${type}\`)
      const data = await client.query(config.list, options)
      const key = Object.keys(data)[0]
      return data[key]?.nodes ?? []
    },
    async getEntry(type, id) {
      const config = QUERIES[type]
      if (!config) throw new Error(\`No query defined for type: \${type}\`)
      const data = await client.query(config.single, { id })
      const key = Object.keys(data)[0]
      return data[key] ?? null
    },
    async getByPath(path) {
      return client.queryByPath(path, ROUTE_QUERY)
    },
    async getPage(path) {
      return client.queryByPath(path, PAGE_QUERY)
    },
    async raw(query, variables) {
      return client.query(query, variables)
    },
  }
}
`
