// Auto-generated by horizon-drupal-client codegen.
// Run `npx horizon-schema sync` to regenerate.
// DO NOT EDIT — changes will be overwritten.

import type { HorizonClient } from 'horizon-drupal-client'
import type { DrupalNode, DrupalParagraph, DrupalTerm } from 'horizon-drupal-client'
import type { Text, TextSummary, Image, Link, DateTime, Address, Geofield, DateRange } from 'horizon-drupal-client'
import type { QueryOptions } from 'horizon-drupal-client'

// ─── Node Types ────────────────────────────────────────────────────

export interface NodeArticleDetail extends DrupalNode {
  __typename: 'NodeArticleDetail'
  body?: TextSummary
  csvId?: string
  eyebrowText?: string
  heroImage?: any
  seasons?: TermUnion[]
  tags?: TermUnion[]
  topicTags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeArticlePage extends DrupalNode {
  __typename: 'NodeArticlePage'
  content?: ParagraphUnion[]
  csvId?: string
  eyebrowText?: string
  heroImage?: any
  seasons?: TermUnion[]
  tags?: TermUnion[]
  topicTags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeBeachDetailPage extends DrupalNode {
  __typename: 'NodeBeachDetailPage'
  address?: Address
  body?: TextSummary
  csvId?: string
  galleryImages?: any[]
  geofield?: Geofield
  heroImage?: any
  image?: any
  seasons?: TermUnion[]
  tags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeBusiness extends DrupalNode {
  __typename: 'NodeBusiness'
  address?: Address
  body?: TextSummary
  bookingWebsite?: string
  csvId?: string
  email?: string
  geofield?: Geofield
  googleReviews?: string
  image?: any
  mainPhone?: string
  mainWebsite?: string
  noOfReviews?: number
  placeId?: string
  seasons?: TermUnion[]
  tags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeEventDetail extends DrupalNode {
  __typename: 'NodeEventDetail'
  address?: Address
  body?: TextSummary
  bookingWebsite?: string
  csvId?: string
  dateRange?: DateRange[]
  email?: string
  galleryImages?: any[]
  geofield?: Geofield
  heroImage?: any
  mainPhone?: string
  mainWebsite?: string
  seasons?: TermUnion[]
  tags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeLanding extends DrupalNode {
  __typename: 'NodeLanding'
  content?: ParagraphUnion[]
}

export interface NodePage extends DrupalNode {
  __typename: 'NodePage'
  body?: TextSummary
}

// ─── Paragraph Types ───────────────────────────────────────────────

export interface ParagraphAccordion extends DrupalParagraph {
  __typename: 'ParagraphAccordion'
  accordionFieldset?: ParagraphUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphAccordionFieldset extends DrupalParagraph {
  __typename: 'ParagraphAccordionFieldset'
  body?: Text
  title?: string
}

export interface ParagraphArticle extends DrupalParagraph {
  __typename: 'ParagraphArticle'
  articleItems?: NodeUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphAside extends DrupalParagraph {
  __typename: 'ParagraphAside'
  asideFieldset?: ParagraphUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  featureFunctionality?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphAsideFieldset extends DrupalParagraph {
  __typename: 'ParagraphAsideFieldset'
  backgroundColorFieldset?: ParagraphUnion
  badge?: string
  body?: Text
  desktopAspectRatio?: string
  image?: any
  imagePosition?: string
  linkAlignment?: string
  links?: Link[]
  mobileAspectRatio?: string
  title?: string
}

export interface ParagraphBackgroundColorFieldset extends DrupalParagraph {
  __typename: 'ParagraphBackgroundColorFieldset'
  backgroundColorName?: string
  backgroundColorWeight?: string
}

export interface ParagraphBasic extends DrupalParagraph {
  __typename: 'ParagraphBasic'
  backgroundColorFieldset?: ParagraphUnion
  basicFieldset?: ParagraphUnion[]
  container?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphBasicFieldset extends DrupalParagraph {
  __typename: 'ParagraphBasicFieldset'
  body?: Text
  linkAlignment?: string
  links?: Link[]
}

export interface ParagraphBgFieldset extends DrupalParagraph {
  __typename: 'ParagraphBgFieldset'
  bgName?: string
  bgWeight?: string
}

export interface ParagraphCard extends DrupalParagraph {
  __typename: 'ParagraphCard'
  backgroundColorFieldset?: ParagraphUnion
  cardsFieldset?: ParagraphUnion[]
  columnCount?: string
  container?: string
  contentOrientation?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphCardsFieldset extends DrupalParagraph {
  __typename: 'ParagraphCardsFieldset'
  badge?: string
  body?: Text
  image?: any
  links?: Link[]
  title?: string
}

export interface ParagraphCategoryRow extends DrupalParagraph {
  __typename: 'ParagraphCategoryRow'
  categoryLabels?: string[]
  title?: string
}

export interface ParagraphEvent extends DrupalParagraph {
  __typename: 'ParagraphEvent'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphGuide extends DrupalParagraph {
  __typename: 'ParagraphGuide'
  articleItems?: NodeUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphGuideBuilder extends DrupalParagraph {
  __typename: 'ParagraphGuideBuilder'
  backgroundColorFieldset?: ParagraphUnion
  body?: Text
  container?: string
  links?: Link[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphGuideFeature extends DrupalParagraph {
  __typename: 'ParagraphGuideFeature'
  articleItems?: NodeUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
}

export interface ParagraphHero extends DrupalParagraph {
  __typename: 'ParagraphHero'
  container?: string
  desktopAspectRatio?: string
  eyebrow?: string
  featureFunctionality?: string
  linkAlignment?: string
  mobileAspectRatio?: string
  searchLabel?: string
  spacingFieldset?: ParagraphUnion
  title?: string
  videoFile?: File
}

export interface ParagraphListing extends DrupalParagraph {
  __typename: 'ParagraphListing'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  listingFieldset?: ParagraphUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphListingFieldset extends DrupalParagraph {
  __typename: 'ParagraphListingFieldset'
  badge?: string
  body?: Text
  eyebrow?: string
  image?: any
  links?: Link[]
  title?: string
}

export interface ParagraphMarquee extends DrupalParagraph {
  __typename: 'ParagraphMarquee'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  gallery?: any[]
  marqueeDirection?: string
  marqueeSpeed?: string
  showFade?: boolean
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphNewsletter extends DrupalParagraph {
  __typename: 'ParagraphNewsletter'
  backgroundColorFieldset?: ParagraphUnion
  body?: Text
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPerson extends DrupalParagraph {
  __typename: 'ParagraphPerson'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  personFieldset?: ParagraphUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPersonFieldset extends DrupalParagraph {
  __typename: 'ParagraphPersonFieldset'
  badge?: string
  body?: Text
  image?: any
  links?: Link[]
  title?: string
}

export interface ParagraphPlace extends DrupalParagraph {
  __typename: 'ParagraphPlace'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  locationItems?: NodeUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPreference extends DrupalParagraph {
  __typename: 'ParagraphPreference'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPromo extends DrupalParagraph {
  __typename: 'ParagraphPromo'
  backgroundColorFieldset?: ParagraphUnion
  body?: Text
  container?: string
  displayType?: string
  image?: any
  links?: Link[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphQuickLink extends DrupalParagraph {
  __typename: 'ParagraphQuickLink'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  quickLinkFieldset?: ParagraphUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphQuickLinkFieldset extends DrupalParagraph {
  __typename: 'ParagraphQuickLinkFieldset'
  iconName?: string
  links?: Link[]
  title?: string
}

export interface ParagraphSpacingFieldset extends DrupalParagraph {
  __typename: 'ParagraphSpacingFieldset'
  gap?: string
  spacingBottom?: string
  spacingLeft?: string
  spacingRight?: string
  spacingTop?: string
}

export interface ParagraphStatFieldset extends DrupalParagraph {
  __typename: 'ParagraphStatFieldset'
  iconName?: string
  statValue?: string
  title?: string
}

export interface ParagraphStatRow extends DrupalParagraph {
  __typename: 'ParagraphStatRow'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  spacingFieldset?: ParagraphUnion
  statFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTab extends DrupalParagraph {
  __typename: 'ParagraphTab'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  tabsFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTabsFieldset extends DrupalParagraph {
  __typename: 'ParagraphTabsFieldset'
  body?: Text
  title?: string
}

export interface ParagraphTestimonial extends DrupalParagraph {
  __typename: 'ParagraphTestimonial'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  testimonialFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTestimonialFieldset extends DrupalParagraph {
  __typename: 'ParagraphTestimonialFieldset'
  badge?: string
  body?: Text
  image?: any
  title?: string
}

export interface ParagraphTimeline extends DrupalParagraph {
  __typename: 'ParagraphTimeline'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  timelineFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTimelineFieldset extends DrupalParagraph {
  __typename: 'ParagraphTimelineFieldset'
  badge?: string
  body?: Text
  image?: any
  links?: Link[]
  title?: string
}

export interface ParagraphVibe extends DrupalParagraph {
  __typename: 'ParagraphVibe'
  eyebrow?: string
  title?: string
}

export interface ParagraphVideo extends DrupalParagraph {
  __typename: 'ParagraphVideo'
  container?: string
  title?: string
  video?: any
  videoFieldset?: ParagraphUnion[]
}

export interface ParagraphVideoFieldset extends DrupalParagraph {
  __typename: 'ParagraphVideoFieldset'
  body?: Text
  linkAlignment?: string
  links?: Link[]
}

// ─── Term Types ────────────────────────────────────────────────────

export interface TermAmenity extends DrupalTerm {
  __typename: 'TermAmenity'
  parent?: TermUnion
  weight?: number
}

export interface TermCategory extends DrupalTerm {
  __typename: 'TermCategory'
  parent?: TermUnion
  weight?: number
}

export interface TermSeason extends DrupalTerm {
  __typename: 'TermSeason'
  parent?: TermUnion
  weight?: number
}

export interface TermTag extends DrupalTerm {
  __typename: 'TermTag'
  parent?: TermUnion
  weight?: number
}

export interface TermTravelerType extends DrupalTerm {
  __typename: 'TermTravelerType'
  parent?: TermUnion
  weight?: number
}

export interface TermVibe extends DrupalTerm {
  __typename: 'TermVibe'
  icon?: string
  parent?: TermUnion
  weight?: number
}

// ─── Union Types ───────────────────────────────────────────────────

export type ParagraphUnion = ParagraphAccordion | ParagraphAccordionFieldset | ParagraphArticle | ParagraphAside | ParagraphAsideFieldset | ParagraphBackgroundColorFieldset | ParagraphBasic | ParagraphBasicFieldset | ParagraphBgFieldset | ParagraphCard | ParagraphCardsFieldset | ParagraphCategoryRow | ParagraphEvent | ParagraphGuide | ParagraphGuideBuilder | ParagraphGuideFeature | ParagraphHero | ParagraphListing | ParagraphListingFieldset | ParagraphMarquee | ParagraphNewsletter | ParagraphPerson | ParagraphPersonFieldset | ParagraphPlace | ParagraphPreference | ParagraphPromo | ParagraphQuickLink | ParagraphQuickLinkFieldset | ParagraphSpacingFieldset | ParagraphStatFieldset | ParagraphStatRow | ParagraphTab | ParagraphTabsFieldset | ParagraphTestimonial | ParagraphTestimonialFieldset | ParagraphTimeline | ParagraphTimelineFieldset | ParagraphVibe | ParagraphVideo | ParagraphVideoFieldset

export type NodeUnion = NodeArticleDetail | NodeArticlePage | NodeBeachDetailPage | NodeBusiness | NodeEventDetail | NodeLanding | NodePage

export type TermUnion = TermAmenity | TermCategory | TermSeason | TermTag | TermTravelerType | TermVibe

export type RouteEntityUnion = NodeArticleDetail | NodeArticlePage | NodeBeachDetailPage | NodeBusiness | NodeEventDetail | NodeLanding | NodePage

// ─── Content Type Map ───────────────────────────────────────────────

export type ContentNode = NodeArticleDetail | NodeArticlePage | NodeBeachDetailPage | NodeBusiness | NodeEventDetail | NodeLanding | NodePage

export type ContentTypeName = 'NodeArticleDetail' | 'NodeArticlePage' | 'NodeBeachDetailPage' | 'NodeBusiness' | 'NodeEventDetail' | 'NodeLanding' | 'NodePage'

export interface ContentTypeMap {
  NodeArticleDetail: NodeArticleDetail
  NodeArticlePage: NodeArticlePage
  NodeBeachDetailPage: NodeBeachDetailPage
  NodeBusiness: NodeBusiness
  NodeEventDetail: NodeEventDetail
  NodeLanding: NodeLanding
  NodePage: NodePage
}

// ─── Generated GraphQL Queries ──────────────────────────────────────

export const QUERIES: Record<ContentTypeName, { list: string; single: string }> = {
  NodeArticleDetail: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeArticleDetails(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeArticleDetail { body { value processed format summary } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeArticleDetail { body { value processed format summary } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeArticlePage: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeArticlePages(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeArticlePage { csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeArticlePage { csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeBeachDetailPage: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeBeachDetailPages(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeBeachDetailPage { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } csvId galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } image { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeBeachDetailPage { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } csvId galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } image { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeBusiness: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeBusinesss(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeBusiness { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId email geofield { value geoType lat lon left top right bottom geohash latlon } googleReviews image { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite noOfReviews placeId seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeBusiness { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId email geofield { value geoType lat lon left top right bottom geohash latlon } googleReviews image { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite noOfReviews placeId seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeEventDetail: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeEventDetails(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeEventDetail { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId dateRange { start end } email galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeEventDetail { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId dateRange { start end } email galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeLanding: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeLandings(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
      }
    }`,
  },
  NodePage: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodePages(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodePage { body { value processed format summary } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodePage { body { value processed format summary } }
      }
    }`,
  },
} as const

// ─── Route Query (simple entity resolution — no paragraph content) ──

export const ROUTE_QUERY = `
  query ($path: String!) {
    route(path: $path) {
      ... on RouteInternal {
        entity {
          ... on NodeArticleDetail { __typename id title path created { time } changed { time } body { value processed format summary } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeArticlePage { __typename id title path created { time } changed { time } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeBeachDetailPage { __typename id title path created { time } changed { time } address body { value processed format summary } csvId galleryImages { ... on MediaImage { mediaImage { url } } } geofield heroImage { ... on MediaImage { mediaImage { url } } } image { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeBusiness { __typename id title path created { time } changed { time } address body { value processed format summary } bookingWebsite csvId email geofield googleReviews image { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite noOfReviews placeId seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeEventDetail { __typename id title path created { time } changed { time } address body { value processed format summary } bookingWebsite csvId dateRange email galleryImages { ... on MediaImage { mediaImage { url } } } geofield heroImage { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeLanding { __typename id title path created { time } changed { time } }
          ... on NodePage { __typename id title path created { time } changed { time } body { value processed format summary } }
        }
      }
    }
  }
`

// ─── Page Query (with full paragraph content) ──────────────────────

export const PAGE_QUERY = `
  query ($path: String!) {
    route(path: $path) {
      ... on RouteInternal {
        entity {
          ... on NodeArticlePage { __typename id title path created { time } changed { time } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } content {
              ... on ParagraphAccordion { __typename id accordion_accordionFieldset: accordionFieldset { ... on ParagraphAccordionFieldset { id body { value processed format } title } } accordion_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } accordion_container: container accordion_displayType: displayType accordion_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } accordion_title: title }
              ... on ParagraphAccordionFieldset { __typename id accordionFieldset_body: body { value processed format } accordionFieldset_title: title }
              ... on ParagraphArticle { __typename id article_articleItems: articleItems { ... on NodeInterface { id title path } } article_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } article_container: container article_displayType: displayType article_eyebrow: eyebrow article_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } article_title: title }
              ... on ParagraphAside { __typename id aside_asideFieldset: asideFieldset { ... on ParagraphAsideFieldset { id badge body { value processed format } desktopAspectRatio image { ... on MediaImage { mediaImage { url } } } imagePosition linkAlignment links { title url internal } mobileAspectRatio title } } aside_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } aside_container: container aside_displayType: displayType aside_featureFunctionality: featureFunctionality aside_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } aside_title: title }
              ... on ParagraphAsideFieldset { __typename id asideFieldset_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } asideFieldset_badge: badge asideFieldset_body: body { value processed format } asideFieldset_desktopAspectRatio: desktopAspectRatio asideFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } asideFieldset_imagePosition: imagePosition asideFieldset_linkAlignment: linkAlignment asideFieldset_links: links { title url internal } asideFieldset_mobileAspectRatio: mobileAspectRatio asideFieldset_title: title }
              ... on ParagraphBackgroundColorFieldset { __typename id backgroundColorFieldset_backgroundColorName: backgroundColorName backgroundColorFieldset_backgroundColorWeight: backgroundColorWeight }
              ... on ParagraphBasic { __typename id basic_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } basic_basicFieldset: basicFieldset { ... on ParagraphBasicFieldset { id body { value processed format } linkAlignment links { title url internal } } } basic_container: container basic_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } basic_title: title }
              ... on ParagraphBasicFieldset { __typename id basicFieldset_body: body { value processed format } basicFieldset_linkAlignment: linkAlignment basicFieldset_links: links { title url internal } }
              ... on ParagraphBgFieldset { __typename id bgFieldset_bgName: bgName bgFieldset_bgWeight: bgWeight }
              ... on ParagraphCard { __typename id card_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } card_cardsFieldset: cardsFieldset { ... on ParagraphCardsFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } card_columnCount: columnCount card_container: container card_contentOrientation: contentOrientation card_displayType: displayType card_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } card_title: title }
              ... on ParagraphCardsFieldset { __typename id cardsFieldset_badge: badge cardsFieldset_body: body { value processed format } cardsFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } cardsFieldset_links: links { title url internal } cardsFieldset_title: title }
              ... on ParagraphCategoryRow { __typename id categoryRow_categoryLabels: categoryLabels categoryRow_title: title }
              ... on ParagraphEvent { __typename id event_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } event_container: container event_displayType: displayType event_eyebrow: eyebrow event_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } event_title: title }
              ... on ParagraphGuide { __typename id guide_articleItems: articleItems { ... on NodeInterface { id title path } } guide_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } guide_container: container guide_displayType: displayType guide_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } guide_title: title }
              ... on ParagraphGuideBuilder { __typename id guideBuilder_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } guideBuilder_body: body { value processed format } guideBuilder_container: container guideBuilder_links: links { title url internal } guideBuilder_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } guideBuilder_title: title }
              ... on ParagraphGuideFeature { __typename id guideFeature_articleItems: articleItems { ... on NodeInterface { id title path } } guideFeature_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } guideFeature_container: container guideFeature_displayType: displayType guideFeature_eyebrow: eyebrow guideFeature_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } }
              ... on ParagraphHero { __typename id hero_container: container hero_desktopAspectRatio: desktopAspectRatio hero_eyebrow: eyebrow hero_featureFunctionality: featureFunctionality hero_linkAlignment: linkAlignment hero_mobileAspectRatio: mobileAspectRatio hero_searchLabel: searchLabel hero_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } hero_title: title hero_videoFile: videoFile { name url size mime description } }
              ... on ParagraphListing { __typename id listing_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } listing_container: container listing_displayType: displayType listing_listingFieldset: listingFieldset { ... on ParagraphListingFieldset { id badge body { value processed format } eyebrow image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } listing_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } listing_title: title }
              ... on ParagraphListingFieldset { __typename id listingFieldset_badge: badge listingFieldset_body: body { value processed format } listingFieldset_eyebrow: eyebrow listingFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } listingFieldset_links: links { title url internal } listingFieldset_title: title }
              ... on ParagraphMarquee { __typename id marquee_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } marquee_container: container marquee_gallery: gallery { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } marquee_marqueeDirection: marqueeDirection marquee_marqueeSpeed: marqueeSpeed marquee_showFade: showFade marquee_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } marquee_title: title }
              ... on ParagraphNewsletter { __typename id newsletter_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } newsletter_body: body { value processed format } newsletter_container: container newsletter_displayType: displayType newsletter_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } newsletter_title: title }
              ... on ParagraphPerson { __typename id person_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } person_container: container person_displayType: displayType person_eyebrow: eyebrow person_personFieldset: personFieldset { ... on ParagraphPersonFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } person_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } person_title: title }
              ... on ParagraphPersonFieldset { __typename id personFieldset_badge: badge personFieldset_body: body { value processed format } personFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } personFieldset_links: links { title url internal } personFieldset_title: title }
              ... on ParagraphPlace { __typename id place_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } place_container: container place_displayType: displayType place_eyebrow: eyebrow place_locationItems: locationItems { ... on NodeInterface { id title path } } place_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } place_title: title }
              ... on ParagraphPreference { __typename id preference_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } preference_container: container preference_eyebrow: eyebrow preference_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } preference_title: title }
              ... on ParagraphPromo { __typename id promo_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } promo_body: body { value processed format } promo_container: container promo_displayType: displayType promo_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } promo_links: links { title url internal } promo_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } promo_title: title }
              ... on ParagraphQuickLink { __typename id quickLink_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } quickLink_container: container quickLink_quickLinkFieldset: quickLinkFieldset { ... on ParagraphQuickLinkFieldset { id iconName links { title url internal } title } } quickLink_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } quickLink_title: title }
              ... on ParagraphQuickLinkFieldset { __typename id quickLinkFieldset_iconName: iconName quickLinkFieldset_links: links { title url internal } quickLinkFieldset_title: title }
              ... on ParagraphSpacingFieldset { __typename id spacingFieldset_gap: gap spacingFieldset_spacingBottom: spacingBottom spacingFieldset_spacingLeft: spacingLeft spacingFieldset_spacingRight: spacingRight spacingFieldset_spacingTop: spacingTop }
              ... on ParagraphStatFieldset { __typename id statFieldset_iconName: iconName statFieldset_statValue: statValue statFieldset_title: title }
              ... on ParagraphStatRow { __typename id statRow_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } statRow_container: container statRow_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } statRow_statFieldset: statFieldset { ... on ParagraphStatFieldset { id iconName statValue title } } statRow_title: title }
              ... on ParagraphTab { __typename id tab_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } tab_container: container tab_displayType: displayType tab_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } tab_tabsFieldset: tabsFieldset { ... on ParagraphTabsFieldset { id body { value processed format } title } } tab_title: title }
              ... on ParagraphTabsFieldset { __typename id tabsFieldset_body: body { value processed format } tabsFieldset_title: title }
              ... on ParagraphTestimonial { __typename id testimonial_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } testimonial_container: container testimonial_displayType: displayType testimonial_eyebrow: eyebrow testimonial_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } testimonial_testimonialFieldset: testimonialFieldset { ... on ParagraphTestimonialFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } title } } testimonial_title: title }
              ... on ParagraphTestimonialFieldset { __typename id testimonialFieldset_badge: badge testimonialFieldset_body: body { value processed format } testimonialFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } testimonialFieldset_title: title }
              ... on ParagraphTimeline { __typename id timeline_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } timeline_container: container timeline_displayType: displayType timeline_eyebrow: eyebrow timeline_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } timeline_timelineFieldset: timelineFieldset { ... on ParagraphTimelineFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } timeline_title: title }
              ... on ParagraphTimelineFieldset { __typename id timelineFieldset_badge: badge timelineFieldset_body: body { value processed format } timelineFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } timelineFieldset_links: links { title url internal } timelineFieldset_title: title }
              ... on ParagraphVibe { __typename id vibe_eyebrow: eyebrow vibe_title: title }
              ... on ParagraphVideo { __typename id video_container: container video_title: title video_video: video { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } video_videoFieldset: videoFieldset { ... on ParagraphVideoFieldset { id body { value processed format } linkAlignment links { title url internal } } } }
              ... on ParagraphVideoFieldset { __typename id videoFieldset_body: body { value processed format } videoFieldset_linkAlignment: linkAlignment videoFieldset_links: links { title url internal } }
            } }
          ... on NodeLanding { __typename id title path created { time } changed { time } content {
              ... on ParagraphAccordion { __typename id accordion_accordionFieldset: accordionFieldset { ... on ParagraphAccordionFieldset { id body { value processed format } title } } accordion_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } accordion_container: container accordion_displayType: displayType accordion_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } accordion_title: title }
              ... on ParagraphAccordionFieldset { __typename id accordionFieldset_body: body { value processed format } accordionFieldset_title: title }
              ... on ParagraphArticle { __typename id article_articleItems: articleItems { ... on NodeInterface { id title path } } article_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } article_container: container article_displayType: displayType article_eyebrow: eyebrow article_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } article_title: title }
              ... on ParagraphAside { __typename id aside_asideFieldset: asideFieldset { ... on ParagraphAsideFieldset { id badge body { value processed format } desktopAspectRatio image { ... on MediaImage { mediaImage { url } } } imagePosition linkAlignment links { title url internal } mobileAspectRatio title } } aside_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } aside_container: container aside_displayType: displayType aside_featureFunctionality: featureFunctionality aside_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } aside_title: title }
              ... on ParagraphAsideFieldset { __typename id asideFieldset_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } asideFieldset_badge: badge asideFieldset_body: body { value processed format } asideFieldset_desktopAspectRatio: desktopAspectRatio asideFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } asideFieldset_imagePosition: imagePosition asideFieldset_linkAlignment: linkAlignment asideFieldset_links: links { title url internal } asideFieldset_mobileAspectRatio: mobileAspectRatio asideFieldset_title: title }
              ... on ParagraphBackgroundColorFieldset { __typename id backgroundColorFieldset_backgroundColorName: backgroundColorName backgroundColorFieldset_backgroundColorWeight: backgroundColorWeight }
              ... on ParagraphBasic { __typename id basic_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } basic_basicFieldset: basicFieldset { ... on ParagraphBasicFieldset { id body { value processed format } linkAlignment links { title url internal } } } basic_container: container basic_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } basic_title: title }
              ... on ParagraphBasicFieldset { __typename id basicFieldset_body: body { value processed format } basicFieldset_linkAlignment: linkAlignment basicFieldset_links: links { title url internal } }
              ... on ParagraphBgFieldset { __typename id bgFieldset_bgName: bgName bgFieldset_bgWeight: bgWeight }
              ... on ParagraphCard { __typename id card_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } card_cardsFieldset: cardsFieldset { ... on ParagraphCardsFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } card_columnCount: columnCount card_container: container card_contentOrientation: contentOrientation card_displayType: displayType card_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } card_title: title }
              ... on ParagraphCardsFieldset { __typename id cardsFieldset_badge: badge cardsFieldset_body: body { value processed format } cardsFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } cardsFieldset_links: links { title url internal } cardsFieldset_title: title }
              ... on ParagraphCategoryRow { __typename id categoryRow_categoryLabels: categoryLabels categoryRow_title: title }
              ... on ParagraphEvent { __typename id event_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } event_container: container event_displayType: displayType event_eyebrow: eyebrow event_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } event_title: title }
              ... on ParagraphGuide { __typename id guide_articleItems: articleItems { ... on NodeInterface { id title path } } guide_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } guide_container: container guide_displayType: displayType guide_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } guide_title: title }
              ... on ParagraphGuideBuilder { __typename id guideBuilder_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } guideBuilder_body: body { value processed format } guideBuilder_container: container guideBuilder_links: links { title url internal } guideBuilder_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } guideBuilder_title: title }
              ... on ParagraphGuideFeature { __typename id guideFeature_articleItems: articleItems { ... on NodeInterface { id title path } } guideFeature_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } guideFeature_container: container guideFeature_displayType: displayType guideFeature_eyebrow: eyebrow guideFeature_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } }
              ... on ParagraphHero { __typename id hero_container: container hero_desktopAspectRatio: desktopAspectRatio hero_eyebrow: eyebrow hero_featureFunctionality: featureFunctionality hero_linkAlignment: linkAlignment hero_mobileAspectRatio: mobileAspectRatio hero_searchLabel: searchLabel hero_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } hero_title: title hero_videoFile: videoFile { name url size mime description } }
              ... on ParagraphListing { __typename id listing_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } listing_container: container listing_displayType: displayType listing_listingFieldset: listingFieldset { ... on ParagraphListingFieldset { id badge body { value processed format } eyebrow image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } listing_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } listing_title: title }
              ... on ParagraphListingFieldset { __typename id listingFieldset_badge: badge listingFieldset_body: body { value processed format } listingFieldset_eyebrow: eyebrow listingFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } listingFieldset_links: links { title url internal } listingFieldset_title: title }
              ... on ParagraphMarquee { __typename id marquee_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } marquee_container: container marquee_gallery: gallery { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } marquee_marqueeDirection: marqueeDirection marquee_marqueeSpeed: marqueeSpeed marquee_showFade: showFade marquee_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } marquee_title: title }
              ... on ParagraphNewsletter { __typename id newsletter_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } newsletter_body: body { value processed format } newsletter_container: container newsletter_displayType: displayType newsletter_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } newsletter_title: title }
              ... on ParagraphPerson { __typename id person_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } person_container: container person_displayType: displayType person_eyebrow: eyebrow person_personFieldset: personFieldset { ... on ParagraphPersonFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } person_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } person_title: title }
              ... on ParagraphPersonFieldset { __typename id personFieldset_badge: badge personFieldset_body: body { value processed format } personFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } personFieldset_links: links { title url internal } personFieldset_title: title }
              ... on ParagraphPlace { __typename id place_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } place_container: container place_displayType: displayType place_eyebrow: eyebrow place_locationItems: locationItems { ... on NodeInterface { id title path } } place_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } place_title: title }
              ... on ParagraphPreference { __typename id preference_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } preference_container: container preference_eyebrow: eyebrow preference_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } preference_title: title }
              ... on ParagraphPromo { __typename id promo_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } promo_body: body { value processed format } promo_container: container promo_displayType: displayType promo_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } promo_links: links { title url internal } promo_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } promo_title: title }
              ... on ParagraphQuickLink { __typename id quickLink_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } quickLink_container: container quickLink_quickLinkFieldset: quickLinkFieldset { ... on ParagraphQuickLinkFieldset { id iconName links { title url internal } title } } quickLink_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } quickLink_title: title }
              ... on ParagraphQuickLinkFieldset { __typename id quickLinkFieldset_iconName: iconName quickLinkFieldset_links: links { title url internal } quickLinkFieldset_title: title }
              ... on ParagraphSpacingFieldset { __typename id spacingFieldset_gap: gap spacingFieldset_spacingBottom: spacingBottom spacingFieldset_spacingLeft: spacingLeft spacingFieldset_spacingRight: spacingRight spacingFieldset_spacingTop: spacingTop }
              ... on ParagraphStatFieldset { __typename id statFieldset_iconName: iconName statFieldset_statValue: statValue statFieldset_title: title }
              ... on ParagraphStatRow { __typename id statRow_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } statRow_container: container statRow_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } statRow_statFieldset: statFieldset { ... on ParagraphStatFieldset { id iconName statValue title } } statRow_title: title }
              ... on ParagraphTab { __typename id tab_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } tab_container: container tab_displayType: displayType tab_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } tab_tabsFieldset: tabsFieldset { ... on ParagraphTabsFieldset { id body { value processed format } title } } tab_title: title }
              ... on ParagraphTabsFieldset { __typename id tabsFieldset_body: body { value processed format } tabsFieldset_title: title }
              ... on ParagraphTestimonial { __typename id testimonial_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } testimonial_container: container testimonial_displayType: displayType testimonial_eyebrow: eyebrow testimonial_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } testimonial_testimonialFieldset: testimonialFieldset { ... on ParagraphTestimonialFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } title } } testimonial_title: title }
              ... on ParagraphTestimonialFieldset { __typename id testimonialFieldset_badge: badge testimonialFieldset_body: body { value processed format } testimonialFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } testimonialFieldset_title: title }
              ... on ParagraphTimeline { __typename id timeline_backgroundColorFieldset: backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } timeline_container: container timeline_displayType: displayType timeline_eyebrow: eyebrow timeline_spacingFieldset: spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } timeline_timelineFieldset: timelineFieldset { ... on ParagraphTimelineFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } timeline_title: title }
              ... on ParagraphTimelineFieldset { __typename id timelineFieldset_badge: badge timelineFieldset_body: body { value processed format } timelineFieldset_image: image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } timelineFieldset_links: links { title url internal } timelineFieldset_title: title }
              ... on ParagraphVibe { __typename id vibe_eyebrow: eyebrow vibe_title: title }
              ... on ParagraphVideo { __typename id video_container: container video_title: title video_video: video { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } video_videoFieldset: videoFieldset { ... on ParagraphVideoFieldset { id body { value processed format } linkAlignment links { title url internal } } } }
              ... on ParagraphVideoFieldset { __typename id videoFieldset_body: body { value processed format } videoFieldset_linkAlignment: linkAlignment videoFieldset_links: links { title url internal } }
            } }
        }
      }
    }
  }
`


// ─── Typed Client ──────────────────────────────────────────────────

export interface TypedClient {
  /** List content entries of a given type */
  getEntries<K extends ContentTypeName>(
    type: K,
    options?: QueryOptions,
  ): Promise<ContentTypeMap[K][]>

  /** Get a single content entry by UUID */
  getEntry<K extends ContentTypeName>(
    type: K,
    id: string,
  ): Promise<ContentTypeMap[K] | null>

  /** Resolve a Drupal path to a typed content node */
  getByPath(path: string): Promise<ContentNode | null>

  /** Get a landing/article page by path (includes paragraph content) */
  getPage(path: string): Promise<ContentNode | null>

  /** Escape hatch: run a raw GraphQL query */
  raw<T = any>(query: string, variables?: Record<string, any>): Promise<T>
}


// ─── Dealias helper ────────────────────────────────────────────────

/**
 * Recursively strip alias prefixes from response keys.
 * Converts "card_title" → "title", "card_displayType" → "displayType", etc.
 * Aliases follow the pattern: {typeName}_{fieldName} where typeName comes
 * from the __typename (e.g. ParagraphCard → "card").
 */
function dealiasResponse(obj: any): any {
  if (obj === null || obj === undefined) return obj
  if (Array.isArray(obj)) return obj.map(dealiasResponse)
  if (typeof obj !== 'object') return obj

  const result: any = {}
  // Determine prefix from __typename if present
  const typeName = obj.__typename as string | undefined
  let prefix = ''
  if (typeName?.startsWith('Paragraph')) {
    const base = typeName.replace('Paragraph', '')
    prefix = base.charAt(0).toLowerCase() + base.slice(1) + '_'
  }

  for (const [key, value] of Object.entries(obj)) {
    // Strip alias prefix if it matches this type's prefix
    let cleanKey = key
    if (prefix && key.startsWith(prefix)) {
      cleanKey = key.slice(prefix.length)
    }
    // Also strip any other common alias patterns (prefix_field format)
    if (cleanKey === key && key.includes('_') && !key.startsWith('__')) {
      const underscoreIdx = key.indexOf('_')
      const possibleField = key.slice(underscoreIdx + 1)
      // Only strip if the part before _ looks like a type prefix (lowercase start)
      if (key.charAt(0) === key.charAt(0).toLowerCase() && possibleField.length > 0) {
        cleanKey = possibleField
      }
    }
    result[cleanKey] = dealiasResponse(value)
  }
  return result
}

// ─── Factory ───────────────────────────────────────────────────────

export function createTypedClient(client: HorizonClient): TypedClient {
  return {
    async getEntries(type, options) {
      const config = QUERIES[type]
      if (!config) throw new Error(`No query defined for type: ${type}`)
      const data = await client.query(config.list, options)
      const key = Object.keys(data)[0]
      return data[key]?.nodes ?? []
    },
    async getEntry(type, id) {
      const config = QUERIES[type]
      if (!config) throw new Error(`No query defined for type: ${type}`)
      const data = await client.query(config.single, { id })
      const key = Object.keys(data)[0]
      return data[key] ?? null
    },
    async getByPath(path) {
      return client.queryByPath(path, ROUTE_QUERY)
    },
    async getPage(path) {
      const entity = await client.queryByPath(path, PAGE_QUERY)
      return entity ? dealiasResponse(entity) : null
    },
    async raw(query, variables) {
      return client.query(query, variables)
    },
  }
}
