// Auto-generated by horizon-drupal-client codegen.
// Run `npx horizon-schema sync` to regenerate.
// DO NOT EDIT — changes will be overwritten.

import type { HorizonClient } from 'horizon-drupal-client'
import type { DrupalNode, DrupalParagraph, DrupalTerm } from 'horizon-drupal-client'
import type { Text, TextSummary, Image, Link, DateTime, Address, Geofield, DateRange } from 'horizon-drupal-client'
import type { QueryOptions } from 'horizon-drupal-client'

// ─── Node Types ────────────────────────────────────────────────────

export interface NodeArticleDetail extends DrupalNode {
  __typename: 'NodeArticleDetail'
  body?: TextSummary
  csvId?: string
  eyebrowText?: string
  heroImage?: MediaUnion
  seasons?: TermUnion[]
  tags?: TermUnion[]
  topicTags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeArticlePage extends DrupalNode {
  __typename: 'NodeArticlePage'
  content?: ParagraphUnion[]
  csvId?: string
  eyebrowText?: string
  heroImage?: MediaUnion
  seasons?: TermUnion[]
  tags?: TermUnion[]
  topicTags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeBeachDetailPage extends DrupalNode {
  __typename: 'NodeBeachDetailPage'
  address?: Address
  body?: TextSummary
  csvId?: string
  galleryImages?: MediaUnion[]
  geofield?: Geospatial
  heroImage?: MediaUnion
  image?: MediaUnion
  seasons?: TermUnion[]
  tags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeBusiness extends DrupalNode {
  __typename: 'NodeBusiness'
  address?: Address
  body?: TextSummary
  bookingWebsite?: string
  csvId?: string
  email?: string
  geofield?: Geospatial
  googleReviews?: string
  image?: MediaUnion
  mainPhone?: string
  mainWebsite?: string
  noOfReviews?: number
  placeId?: string
  seasons?: TermUnion[]
  tags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeEventDetail extends DrupalNode {
  __typename: 'NodeEventDetail'
  address?: Address
  body?: TextSummary
  bookingWebsite?: string
  csvId?: string
  dateRange?: DateRange[]
  email?: string
  galleryImages?: MediaUnion[]
  geofield?: Geospatial
  heroImage?: MediaUnion
  mainPhone?: string
  mainWebsite?: string
  seasons?: TermUnion[]
  tags?: TermUnion[]
  travelerTypes?: TermUnion[]
  vibes?: TermUnion[]
}

export interface NodeLanding extends DrupalNode {
  __typename: 'NodeLanding'
  content?: ParagraphUnion[]
}

export interface NodePage extends DrupalNode {
  __typename: 'NodePage'
  body?: TextSummary
}

// ─── Paragraph Types ───────────────────────────────────────────────

export interface ParagraphAccordion extends DrupalParagraph {
  __typename: 'ParagraphAccordion'
  accordionFieldset?: ParagraphUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphAccordionFieldset extends DrupalParagraph {
  __typename: 'ParagraphAccordionFieldset'
  body?: Text
  title?: string
}

export interface ParagraphArticle extends DrupalParagraph {
  __typename: 'ParagraphArticle'
  articleItems?: NodeUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphAside extends DrupalParagraph {
  __typename: 'ParagraphAside'
  asideFieldset?: ParagraphUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  featureFunctionality?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphAsideFieldset extends DrupalParagraph {
  __typename: 'ParagraphAsideFieldset'
  backgroundColorFieldset?: ParagraphUnion
  badge?: string
  body?: Text
  desktopAspectRatio?: string
  image?: MediaUnion
  imagePosition?: string
  linkAlignment?: string
  links?: Link[]
  mobileAspectRatio?: string
  title?: string
}

export interface ParagraphBackgroundColorFieldset extends DrupalParagraph {
  __typename: 'ParagraphBackgroundColorFieldset'
  backgroundColorName?: string
  backgroundColorWeight?: string
}

export interface ParagraphBasic extends DrupalParagraph {
  __typename: 'ParagraphBasic'
  backgroundColorFieldset?: ParagraphUnion
  basicFieldset?: ParagraphUnion[]
  container?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphBasicFieldset extends DrupalParagraph {
  __typename: 'ParagraphBasicFieldset'
  body?: Text
  linkAlignment?: string
  links?: Link[]
}

export interface ParagraphBgFieldset extends DrupalParagraph {
  __typename: 'ParagraphBgFieldset'
  bgName?: string
  bgWeight?: string
}

export interface ParagraphCard extends DrupalParagraph {
  __typename: 'ParagraphCard'
  backgroundColorFieldset?: ParagraphUnion
  cardsFieldset?: ParagraphUnion[]
  columnCount?: string
  container?: string
  contentOrientation?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphCardsFieldset extends DrupalParagraph {
  __typename: 'ParagraphCardsFieldset'
  badge?: string
  body?: Text
  image?: MediaUnion
  links?: Link[]
  title?: string
}

export interface ParagraphCategoryRow extends DrupalParagraph {
  __typename: 'ParagraphCategoryRow'
  categoryLabels?: string[]
  title?: string
}

export interface ParagraphEvent extends DrupalParagraph {
  __typename: 'ParagraphEvent'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphGuide extends DrupalParagraph {
  __typename: 'ParagraphGuide'
  articleItems?: NodeUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphGuideBuilder extends DrupalParagraph {
  __typename: 'ParagraphGuideBuilder'
  backgroundColorFieldset?: ParagraphUnion
  body?: Text
  container?: string
  links?: Link[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphGuideFeature extends DrupalParagraph {
  __typename: 'ParagraphGuideFeature'
  articleItems?: NodeUnion[]
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
}

export interface ParagraphHero extends DrupalParagraph {
  __typename: 'ParagraphHero'
  container?: string
  desktopAspectRatio?: string
  eyebrow?: string
  featureFunctionality?: string
  linkAlignment?: string
  mobileAspectRatio?: string
  searchLabel?: string
  spacingFieldset?: ParagraphUnion
  title?: string
  videoFile?: File
}

export interface ParagraphListing extends DrupalParagraph {
  __typename: 'ParagraphListing'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  listingFieldset?: ParagraphUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphListingFieldset extends DrupalParagraph {
  __typename: 'ParagraphListingFieldset'
  badge?: string
  body?: Text
  eyebrow?: string
  image?: MediaUnion
  links?: Link[]
  title?: string
}

export interface ParagraphMarquee extends DrupalParagraph {
  __typename: 'ParagraphMarquee'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  gallery?: MediaUnion[]
  marqueeDirection?: string
  marqueeSpeed?: string
  showFade?: boolean
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphNewsletter extends DrupalParagraph {
  __typename: 'ParagraphNewsletter'
  backgroundColorFieldset?: ParagraphUnion
  body?: Text
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPerson extends DrupalParagraph {
  __typename: 'ParagraphPerson'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  personFieldset?: ParagraphUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPersonFieldset extends DrupalParagraph {
  __typename: 'ParagraphPersonFieldset'
  badge?: string
  body?: Text
  image?: MediaUnion
  links?: Link[]
  title?: string
}

export interface ParagraphPlace extends DrupalParagraph {
  __typename: 'ParagraphPlace'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  locationItems?: NodeUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPreference extends DrupalParagraph {
  __typename: 'ParagraphPreference'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphPromo extends DrupalParagraph {
  __typename: 'ParagraphPromo'
  backgroundColorFieldset?: ParagraphUnion
  body?: Text
  container?: string
  displayType?: string
  image?: MediaUnion
  links?: Link[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphQuickLink extends DrupalParagraph {
  __typename: 'ParagraphQuickLink'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  quickLinkFieldset?: ParagraphUnion[]
  spacingFieldset?: ParagraphUnion
  title?: string
}

export interface ParagraphQuickLinkFieldset extends DrupalParagraph {
  __typename: 'ParagraphQuickLinkFieldset'
  iconName?: string
  links?: Link[]
  title?: string
}

export interface ParagraphSpacingFieldset extends DrupalParagraph {
  __typename: 'ParagraphSpacingFieldset'
  gap?: string
  spacingBottom?: string
  spacingLeft?: string
  spacingRight?: string
  spacingTop?: string
}

export interface ParagraphStatFieldset extends DrupalParagraph {
  __typename: 'ParagraphStatFieldset'
  iconName?: string
  statValue?: string
  title?: string
}

export interface ParagraphStatRow extends DrupalParagraph {
  __typename: 'ParagraphStatRow'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  spacingFieldset?: ParagraphUnion
  statFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTab extends DrupalParagraph {
  __typename: 'ParagraphTab'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  spacingFieldset?: ParagraphUnion
  tabsFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTabsFieldset extends DrupalParagraph {
  __typename: 'ParagraphTabsFieldset'
  body?: Text
  title?: string
}

export interface ParagraphTestimonial extends DrupalParagraph {
  __typename: 'ParagraphTestimonial'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  testimonialFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTestimonialFieldset extends DrupalParagraph {
  __typename: 'ParagraphTestimonialFieldset'
  badge?: string
  body?: Text
  image?: MediaUnion
  title?: string
}

export interface ParagraphTimeline extends DrupalParagraph {
  __typename: 'ParagraphTimeline'
  backgroundColorFieldset?: ParagraphUnion
  container?: string
  displayType?: string
  eyebrow?: string
  spacingFieldset?: ParagraphUnion
  timelineFieldset?: ParagraphUnion[]
  title?: string
}

export interface ParagraphTimelineFieldset extends DrupalParagraph {
  __typename: 'ParagraphTimelineFieldset'
  badge?: string
  body?: Text
  image?: MediaUnion
  links?: Link[]
  title?: string
}

export interface ParagraphVibe extends DrupalParagraph {
  __typename: 'ParagraphVibe'
  eyebrow?: string
  title?: string
}

export interface ParagraphVideo extends DrupalParagraph {
  __typename: 'ParagraphVideo'
  container?: string
  title?: string
  video?: MediaUnion
  videoFieldset?: ParagraphUnion[]
}

export interface ParagraphVideoFieldset extends DrupalParagraph {
  __typename: 'ParagraphVideoFieldset'
  body?: Text
  linkAlignment?: string
  links?: Link[]
}

// ─── Term Types ────────────────────────────────────────────────────

export interface TermAmenity extends DrupalTerm {
  __typename: 'TermAmenity'
  parent?: TermUnion
  weight?: number
}

export interface TermCategory extends DrupalTerm {
  __typename: 'TermCategory'
  parent?: TermUnion
  weight?: number
}

export interface TermSeason extends DrupalTerm {
  __typename: 'TermSeason'
  parent?: TermUnion
  weight?: number
}

export interface TermTag extends DrupalTerm {
  __typename: 'TermTag'
  parent?: TermUnion
  weight?: number
}

export interface TermTravelerType extends DrupalTerm {
  __typename: 'TermTravelerType'
  parent?: TermUnion
  weight?: number
}

export interface TermVibe extends DrupalTerm {
  __typename: 'TermVibe'
  icon?: string
  parent?: TermUnion
  weight?: number
}

// ─── Union Types ───────────────────────────────────────────────────

export type ParagraphUnion = ParagraphAccordion | ParagraphAccordionFieldset | ParagraphArticle | ParagraphAside | ParagraphAsideFieldset | ParagraphBackgroundColorFieldset | ParagraphBasic | ParagraphBasicFieldset | ParagraphBgFieldset | ParagraphCard | ParagraphCardsFieldset | ParagraphCategoryRow | ParagraphEvent | ParagraphGuide | ParagraphGuideBuilder | ParagraphGuideFeature | ParagraphHero | ParagraphListing | ParagraphListingFieldset | ParagraphMarquee | ParagraphNewsletter | ParagraphPerson | ParagraphPersonFieldset | ParagraphPlace | ParagraphPreference | ParagraphPromo | ParagraphQuickLink | ParagraphQuickLinkFieldset | ParagraphSpacingFieldset | ParagraphStatFieldset | ParagraphStatRow | ParagraphTab | ParagraphTabsFieldset | ParagraphTestimonial | ParagraphTestimonialFieldset | ParagraphTimeline | ParagraphTimelineFieldset | ParagraphVibe | ParagraphVideo | ParagraphVideoFieldset

export type NodeUnion = NodeArticleDetail | NodeArticlePage | NodeBeachDetailPage | NodeBusiness | NodeEventDetail | NodeLanding | NodePage

export type TermUnion = TermAmenity | TermCategory | TermSeason | TermTag | TermTravelerType | TermVibe

export type RouteEntityUnion = NodeArticleDetail | NodeArticlePage | NodeBeachDetailPage | NodeBusiness | NodeEventDetail | NodeLanding | NodePage

// ─── Content Type Map ───────────────────────────────────────────────

export type ContentNode = NodeArticleDetail | NodeArticlePage | NodeBeachDetailPage | NodeBusiness | NodeEventDetail | NodeLanding | NodePage

export type ContentTypeName = 'NodeArticleDetail' | 'NodeArticlePage' | 'NodeBeachDetailPage' | 'NodeBusiness' | 'NodeEventDetail' | 'NodeLanding' | 'NodePage'

export interface ContentTypeMap {
  NodeArticleDetail: NodeArticleDetail
  NodeArticlePage: NodeArticlePage
  NodeBeachDetailPage: NodeBeachDetailPage
  NodeBusiness: NodeBusiness
  NodeEventDetail: NodeEventDetail
  NodeLanding: NodeLanding
  NodePage: NodePage
}

// ─── Generated GraphQL Queries ──────────────────────────────────────

export const QUERIES: Record<ContentTypeName, { list: string; single: string }> = {
  NodeArticleDetail: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeArticleDetails(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeArticleDetail { body { value processed format summary } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeArticleDetail { body { value processed format summary } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeArticlePage: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeArticlePages(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeArticlePage { csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeArticlePage { csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeBeachDetailPage: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeBeachDetailPages(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeBeachDetailPage { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } csvId galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } image { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeBeachDetailPage { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } csvId galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } image { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeBusiness: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeBusinesss(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeBusiness { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId email geofield { value geoType lat lon left top right bottom geohash latlon } googleReviews image { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite noOfReviews placeId seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeBusiness { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId email geofield { value geoType lat lon left top right bottom geohash latlon } googleReviews image { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite noOfReviews placeId seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeEventDetail: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeEventDetails(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodeEventDetail { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId dateRange { start end } email galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodeEventDetail { address { country givenName additionalName familyName organization addressLine1 addressLine2 postalCode sortingCode dependentLocality locality administrativeArea } body { value processed format summary } bookingWebsite csvId dateRange { start end } email galleryImages { ... on MediaImage { mediaImage { url } } } geofield { value geoType lat lon left top right bottom geohash latlon } heroImage { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
      }
    }`,
  },
  NodeLanding: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodeLandings(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
      }
    }`,
  },
  NodePage: {
    list: `query ($first: Int, $after: Cursor, $sortKey: ConnectionSortKeys, $reverse: Boolean) {
      nodePages(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
        nodes {
          __typename id title path created { time } changed { time }
          ... on NodePage { body { value processed format summary } }
        }
        pageInfo { hasNextPage endCursor }
      }
    }`,
    single: `query ($id: ID!) {
      node(id: $id) {
        __typename id title path created { time } changed { time }
          ... on NodePage { body { value processed format summary } }
      }
    }`,
  },
} as const

// ─── Route Query (simple entity resolution — no paragraph content) ──

export const ROUTE_QUERY = `
  query ($path: String!) {
    route(path: $path) {
      ... on RouteInternal {
        entity {
          ... on NodeArticleDetail { __typename id title path created { time } changed { time } body { value processed format summary } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeArticlePage { __typename id title path created { time } changed { time } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeBeachDetailPage { __typename id title path created { time } changed { time } address body { value processed format summary } csvId galleryImages { ... on MediaImage { mediaImage { url } } } geofield heroImage { ... on MediaImage { mediaImage { url } } } image { ... on MediaImage { mediaImage { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeBusiness { __typename id title path created { time } changed { time } address body { value processed format summary } bookingWebsite csvId email geofield googleReviews image { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite noOfReviews placeId seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeEventDetail { __typename id title path created { time } changed { time } address body { value processed format summary } bookingWebsite csvId dateRange email galleryImages { ... on MediaImage { mediaImage { url } } } geofield heroImage { ... on MediaImage { mediaImage { url } } } mainPhone mainWebsite seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } }
          ... on NodeLanding { __typename id title path created { time } changed { time } }
          ... on NodePage { __typename id title path created { time } changed { time } body { value processed format summary } }
        }
      }
    }
  }
`

// ─── Page Query (with full paragraph content) ──────────────────────

export const PAGE_QUERY = `
  query ($path: String!) {
    route(path: $path) {
      ... on RouteInternal {
        entity {
          ... on NodeArticlePage { __typename id title path created { time } changed { time } csvId eyebrowText heroImage { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } seasons { ... on TermInterface { name } } tags { ... on TermInterface { name } } topicTags { ... on TermInterface { name } } travelerTypes { ... on TermInterface { name } } vibes { ... on TermInterface { name } } content {
              ... on ParagraphAccordion { __typename id accordionFieldset { ... on ParagraphAccordionFieldset { id body { value processed format } title } } backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphAccordionFieldset { __typename id body { value processed format } title }
              ... on ParagraphArticle { __typename id articleItems backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphAside { __typename id asideFieldset { ... on ParagraphAsideFieldset { id badge body { value processed format } desktopAspectRatio image { ... on MediaImage { mediaImage { url } } } imagePosition linkAlignment links { title url internal } mobileAspectRatio title } } backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType featureFunctionality spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphAsideFieldset { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } badge body { value processed format } desktopAspectRatio image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } imagePosition linkAlignment links { title url internal } mobileAspectRatio title }
              ... on ParagraphBackgroundColorFieldset { __typename id backgroundColorName backgroundColorWeight }
              ... on ParagraphBasic { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } basicFieldset { ... on ParagraphBasicFieldset { id body { value processed format } linkAlignment links { title url internal } } } container spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphBasicFieldset { __typename id body { value processed format } linkAlignment links { title url internal } }
              ... on ParagraphBgFieldset { __typename id bgName bgWeight }
              ... on ParagraphCard { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } cardsFieldset { ... on ParagraphCardsFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } columnCount container contentOrientation displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphCardsFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphCategoryRow { __typename id categoryLabels title }
              ... on ParagraphEvent { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphGuide { __typename id articleItems backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphGuideBuilder { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } body { value processed format } container links { title url internal } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphGuideFeature { __typename id articleItems backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } }
              ... on ParagraphHero { __typename id container desktopAspectRatio eyebrow featureFunctionality linkAlignment mobileAspectRatio searchLabel spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title videoFile { name url size mime description } }
              ... on ParagraphListing { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType listingFieldset { ... on ParagraphListingFieldset { id badge body { value processed format } eyebrow image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphListingFieldset { __typename id badge body { value processed format } eyebrow image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphMarquee { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container gallery { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } marqueeDirection marqueeSpeed showFade spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphNewsletter { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } body { value processed format } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPerson { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow personFieldset { ... on ParagraphPersonFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPersonFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphPlace { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow locationItems spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPreference { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPromo { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } body { value processed format } container displayType image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphQuickLink { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container quickLinkFieldset { ... on ParagraphQuickLinkFieldset { id iconName links { title url internal } title } } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphQuickLinkFieldset { __typename id iconName links { title url internal } title }
              ... on ParagraphSpacingFieldset { __typename id gap spacingBottom spacingLeft spacingRight spacingTop }
              ... on ParagraphStatFieldset { __typename id iconName statValue title }
              ... on ParagraphStatRow { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } statFieldset { ... on ParagraphStatFieldset { id iconName statValue title } } title }
              ... on ParagraphTab { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } tabsFieldset { ... on ParagraphTabsFieldset { id body { value processed format } title } } title }
              ... on ParagraphTabsFieldset { __typename id body { value processed format } title }
              ... on ParagraphTestimonial { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } testimonialFieldset { ... on ParagraphTestimonialFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } title } } title }
              ... on ParagraphTestimonialFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } title }
              ... on ParagraphTimeline { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } timelineFieldset { ... on ParagraphTimelineFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } title }
              ... on ParagraphTimelineFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphVibe { __typename id eyebrow title }
              ... on ParagraphVideo { __typename id container title video { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } videoFieldset { ... on ParagraphVideoFieldset { id body { value processed format } linkAlignment links { title url internal } } } }
              ... on ParagraphVideoFieldset { __typename id body { value processed format } linkAlignment links { title url internal } }
            } }
          ... on NodeLanding { __typename id title path created { time } changed { time } content {
              ... on ParagraphAccordion { __typename id accordionFieldset { ... on ParagraphAccordionFieldset { id body { value processed format } title } } backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphAccordionFieldset { __typename id body { value processed format } title }
              ... on ParagraphArticle { __typename id articleItems backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphAside { __typename id asideFieldset { ... on ParagraphAsideFieldset { id badge body { value processed format } desktopAspectRatio image { ... on MediaImage { mediaImage { url } } } imagePosition linkAlignment links { title url internal } mobileAspectRatio title } } backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType featureFunctionality spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphAsideFieldset { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } badge body { value processed format } desktopAspectRatio image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } imagePosition linkAlignment links { title url internal } mobileAspectRatio title }
              ... on ParagraphBackgroundColorFieldset { __typename id backgroundColorName backgroundColorWeight }
              ... on ParagraphBasic { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } basicFieldset { ... on ParagraphBasicFieldset { id body { value processed format } linkAlignment links { title url internal } } } container spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphBasicFieldset { __typename id body { value processed format } linkAlignment links { title url internal } }
              ... on ParagraphBgFieldset { __typename id bgName bgWeight }
              ... on ParagraphCard { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } cardsFieldset { ... on ParagraphCardsFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } columnCount container contentOrientation displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphCardsFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphCategoryRow { __typename id categoryLabels title }
              ... on ParagraphEvent { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphGuide { __typename id articleItems backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphGuideBuilder { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } body { value processed format } container links { title url internal } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphGuideFeature { __typename id articleItems backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } }
              ... on ParagraphHero { __typename id container desktopAspectRatio eyebrow featureFunctionality linkAlignment mobileAspectRatio searchLabel spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title videoFile { name url size mime description } }
              ... on ParagraphListing { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType listingFieldset { ... on ParagraphListingFieldset { id badge body { value processed format } eyebrow image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphListingFieldset { __typename id badge body { value processed format } eyebrow image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphMarquee { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container gallery { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } marqueeDirection marqueeSpeed showFade spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphNewsletter { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } body { value processed format } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPerson { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow personFieldset { ... on ParagraphPersonFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPersonFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphPlace { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow locationItems spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPreference { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphPromo { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } body { value processed format } container displayType image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphQuickLink { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container quickLinkFieldset { ... on ParagraphQuickLinkFieldset { id iconName links { title url internal } title } } spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } title }
              ... on ParagraphQuickLinkFieldset { __typename id iconName links { title url internal } title }
              ... on ParagraphSpacingFieldset { __typename id gap spacingBottom spacingLeft spacingRight spacingTop }
              ... on ParagraphStatFieldset { __typename id iconName statValue title }
              ... on ParagraphStatRow { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } statFieldset { ... on ParagraphStatFieldset { id iconName statValue title } } title }
              ... on ParagraphTab { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } tabsFieldset { ... on ParagraphTabsFieldset { id body { value processed format } title } } title }
              ... on ParagraphTabsFieldset { __typename id body { value processed format } title }
              ... on ParagraphTestimonial { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } testimonialFieldset { ... on ParagraphTestimonialFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } title } } title }
              ... on ParagraphTestimonialFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } title }
              ... on ParagraphTimeline { __typename id backgroundColorFieldset { ... on ParagraphBackgroundColorFieldset { id backgroundColorName backgroundColorWeight } } container displayType eyebrow spacingFieldset { ... on ParagraphSpacingFieldset { id gap spacingBottom spacingLeft spacingRight spacingTop } } timelineFieldset { ... on ParagraphTimelineFieldset { id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } } links { title url internal } title } } title }
              ... on ParagraphTimelineFieldset { __typename id badge body { value processed format } image { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } links { title url internal } title }
              ... on ParagraphVibe { __typename id eyebrow title }
              ... on ParagraphVideo { __typename id container title video { ... on MediaImage { mediaImage { url } } ... on MediaVideo { mediaVideoFile { url } } } videoFieldset { ... on ParagraphVideoFieldset { id body { value processed format } linkAlignment links { title url internal } } } }
              ... on ParagraphVideoFieldset { __typename id body { value processed format } linkAlignment links { title url internal } }
            } }
        }
      }
    }
  }
`


// ─── Typed Client ──────────────────────────────────────────────────

export interface TypedClient {
  /** List content entries of a given type */
  getEntries<K extends ContentTypeName>(
    type: K,
    options?: QueryOptions,
  ): Promise<ContentTypeMap[K][]>

  /** Get a single content entry by UUID */
  getEntry<K extends ContentTypeName>(
    type: K,
    id: string,
  ): Promise<ContentTypeMap[K] | null>

  /** Resolve a Drupal path to a typed content node */
  getByPath(path: string): Promise<ContentNode | null>

  /** Get a landing/article page by path (includes paragraph content) */
  getPage(path: string): Promise<ContentNode | null>

  /** Escape hatch: run a raw GraphQL query */
  raw<T = any>(query: string, variables?: Record<string, any>): Promise<T>
}


// ─── Factory ───────────────────────────────────────────────────────

export function createTypedClient(client: HorizonClient): TypedClient {
  return {
    async getEntries(type, options) {
      const config = QUERIES[type]
      if (!config) throw new Error(`No query defined for type: ${type}`)
      const data = await client.query(config.list, options)
      const key = Object.keys(data)[0]
      return data[key]?.nodes ?? []
    },
    async getEntry(type, id) {
      const config = QUERIES[type]
      if (!config) throw new Error(`No query defined for type: ${type}`)
      const data = await client.query(config.single, { id })
      const key = Object.keys(data)[0]
      return data[key] ?? null
    },
    async getByPath(path) {
      return client.queryByPath(path, ROUTE_QUERY)
    },
    async getPage(path) {
      return client.queryByPath(path, PAGE_QUERY)
    },
    async raw(query, variables) {
      return client.query(query, variables)
    },
  }
}
